// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MockSystem.Data;

namespace MockSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180707123304_intitial")]
    partial class intitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MockSystem.Data.Model.Hospital", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("WardStatus");

                    b.Property<bool>("isAvailable");

                    b.HasKey("Id");

                    b.ToTable("Hospital");
                });

            modelBuilder.Entity("MockSystem.Data.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("HospitalId");

                    b.Property<string>("LastName");

                    b.Property<int>("Occupation");

                    b.Property<int>("StaffId");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MockSystem.Data.Model.User", b =>
                {
                    b.HasOne("MockSystem.Data.Model.Hospital", "Hospital")
                        .WithMany("User")
                        .HasForeignKey("HospitalId");
                });
#pragma warning restore 612, 618
        }
    }
}
